### ISSUE TITLE
Can’t change font style for markdown headings

### ISSUE THREAD

**Issue by vizzmay** [uloco/theme-bluloco-light#12]
I’ve been trying to change font style for markdown headings (`markup.heading`) to bold, but it only works for Bluloco Dark Italic. For the other three themes, the font style remains unchanged.

Examples:

```
"textMateRules": [
    {
        "scope": "markup.heading",
        "settings": {
            "fontStyle": "bold underline"
        }
    }
]
```

Works for Bluloco Dark Italic:

![bluloco-dark-italic](https://user-images.githubusercontent.com/10206339/69257795-a3b02a80-0be1-11ea-880b-ee2b48c3efdd.png)

Doesn’t work for Bluloco Light:

![bluloco-light](https://user-images.githubusercontent.com/10206339/69257812-add22900-0be1-11ea-9e6d-18719dd4a52d.png)

Bluloco Light Italic:

![bluloco-light-italic](https://user-images.githubusercontent.com/10206339/69257840-b7f42780-0be1-11ea-9d95-27e465458ba3.png)

Bluloco Dark:

![bluloco-dark](https://user-images.githubusercontent.com/10206339/69257865-c17d8f80-0be1-11ea-8cdd-066d84585e79.png)

**Comment by uloco** [comment]
Hey, 
try this one here, it worked for me:
```
"editor.tokenColorCustomizations": {
  "[Bluloco Dark]": {
    "textMateRules": [
      {
        "scope": "entity.name.section",
        "settings": {
          "fontStyle": "bold underline"
        }
      }
    ]
  }
}
```
