### ISSUE TITLE
Support for highlighting with C_Cpp.enhancedColorization setting

### ISSUE THREAD

**Issue by allanyjh** [uloco/theme-bluloco-light#15]
About C_Cpp.enhancedColorization setting see: https://code.visualstudio.com/docs/cpp/colorization-cpp

Can you add highlighting for this setting？

Example：

```cpp
#include <string>

using namespace std;

int main(int argc, char *argv[])
{
	string textline;
}
```

The type 'string' should be color highlighting with the scope entity.name.type, when C_Cpp.enhancedColorization is enabled.

Thanks!  :)

**Comment by uloco** [comment]
I don't think this is prossible. I don't know cpp, but even the recommended c++ themes by microsoft do not recognize `string` as something different than text.
Do you mean the `<string>` or `string textline`?

**Comment by uloco** [comment]
You can further install these themes recommended by Microsoft for C/C++ development and check if they work as you expect. If this is the case, I can help you. If no, unfortunately they haven't implemented a correct scope for it, yet.
https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-themes

**Comment by allanyjh** [comment]
I mean `string textline` at line 7. 

A more sophisticated example you can find here:  https://github.com/chester39/EssentialCpp/blob/master/Chapter%203.%20Generic%20Programming/3.3.cpp . In this example, `string` at line 17 and line 19, `vector<string>` at line 20, `string::size_type` at line 21 and line 25,  `ifstream` at line 77, `ofstream` at line 78. They should all recognized as entity.name.type then highlightd as red by bluloco light theme when C_Cpp.enhancedColorization is enabled.

After checking, although using the _Inspect editor tokens and scopes_ to detect that their _foreground_ is equal to the _No theme selector_, they can be enhanced and identified as entity.name.type when the C_Cpp.enhancedColorization setting is enabled.

I used other color themes for testing and they all worked correctly. For example: Atom One Light, Ayu Light, Brackets Light Pro, and of course C/C++ themes recommended by Microsoft.

**Comment by uloco** [comment]
Ok, now I can reproduce. The funny thing is, that vscode will not update the colors when you switch themes, when enhancedColorization is activated. I am not sure how to fix this for now, since there are some other issues related to semantic highlighting, but will look into this as soon as I have time.
Another thing is though, string int etc, are built in types which normally should be colored blue, not red ...

**Comment by uloco** [comment]
Oh, I used real tmTheme (XML) to make the theme portable between sublime text etc. My guts tell me, that this is probably the issue.

**Comment by allanyjh** [comment]
Maybe you are right, because the definition of type in other color themes uses JSON format.

**Comment by allanyjh** [comment]
I've tested the new version and it works fine. Thank you, man.

I want to say that this is the best light color theme for VS Code. :)

**Comment by allanyjh** [comment]
An additional small issue:

In C++, although both `string` and `int` are data types, `int` is the keyword of C++, and `string` is the class of C++ standard function library. If all `string`s (and the same type of syntax units) are highlighted as red, a large number of red blocks will appear in the source code, which visually destroys the effect of Bluloco theme. After applying the new version, that's exactly what happened. So, I agree with your idea of highlighting `string` as blue, while distinguishing it from the keyword `int`. This is how I solved the problem:

Add the following snippets to user settings.json:

```json
"editor.tokenColorCustomizations": {
    "[Bluloco Light]": {
        "textMateRules": [
            {
                "name": "C++ entity.name.type.class",
                "scope": [
                    "source.cpp entity.name.type.class",
                ],
                "settings": {
                    "foreground": "#275fe4"
                }
            }
        ]
    }
}
```

Or, directly add the correction for C++ to Bluloco theme:

```json
{
    "name": "C++ entity.name.type.class",
    "scope": [
        "source.cpp entity.name.type.class",
    ],
    "settings": {
        "foreground": "#275fe4"
    }
}
```

**Comment by uloco** [comment]
Classes and custom types are kind of the same for me, so red makes sense. The blue color you chose is reserved for html/xml tags and those css referencing these only. Because js/html/css is mixed up all of the time, it made sense to me to make these coherent.

Does it make a difference while coding in C/C++ where these types come from? I'd rather say color both the same blue (like keywords) ...

**Comment by allanyjh** [comment]
OK, I agree with you. The above correction is only for personal preference.
