### ISSUE TITLE
Hover on links in the terminal shows a gray box over the link

### ISSUE THREAD

**Issue by moshfeu** [uloco/theme-bluloco-light#17]
Steps:

1. Run `echo https://github.com` in the terminal
2. Hover the link and wait a moment.

It's not reproduced with sample of vscode's themes

![Screen Shot 2020-05-17 at 16 33 42](https://user-images.githubusercontent.com/3723951/82148511-25190a80-985d-11ea-8f21-b043621468ec.png)

Thanks

**Comment by uloco** [comment]
Fixed in ed99822162cadf41d555959a0e07c893400bab69

**Comment by moshfeu** [comment]
Confirmed. Thanks!
