### ISSUE TITLE
It's not looks the same in my vscode

### ISSUE THREAD

**Issue by moshfeu** [uloco/theme-bluloco-light#2]
For example:

**js**
<img width="606" alt="screen shot 2018-10-22 at 1 01 49 pm" src="https://user-images.githubusercontent.com/3723951/47287363-aca78480-d5fa-11e8-89cf-65b9b46e72e0.png">

**ts**
<img width="561" alt="screen shot 2018-10-22 at 1 02 42 pm" src="https://user-images.githubusercontent.com/3723951/47287398-ca74e980-d5fa-11e8-9022-6293a95762dd.png">

I checked and I have nothing in settings that may change the theme colors.

Thanks!

**Comment by uloco** [comment]
This looks like the default Visual Studio Code light theme...
Are you sure you have chosen the right theme in settings? 
`"workbench.colorTheme": "Bluloco Light"`

It could also be, that you have adjusted some theme colors via `"editor.tokenColorCustomizations"`

If this is not the case, your user settings json file would be helpful ...

**Comment by moshfeu** [comment]
After some time it worked (maybe after vscode restart) anyway, now it's working.
Thanks!
