### ISSUE TITLE
schwache schriftfarben 

### ISSUE THREAD

**Issue by pedroanguinoni** [uloco/theme-bluloco-light#30]
Hallo, Umut .. Ich habe eine probleme. 

wie kann ich es in den gleichen farben wie das beispielfoto belassen? meine texte sind schwach .. 

danke

**Comment by uloco** [comment]
Vielleicht hast du in der `settings.json` etwas überschrieben, benutzt eine andere Schriftart oder ein möglicherweise ein Plugin. Kannst du mir bitte deine `settings.json` schicken?

**Comment by pedroanguinoni** [comment]
{
    "workbench.startupEditor": "newUntitledFile",
    "window.zoomLevel": 0,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.colorTheme": "Bluloco Light",
    "editor.fontSize": 13,
    "editor.cursorStyle": "underline",
    "editor.fontWeight": "normal"
    {
        "dark": {
          "bg": "#282c34",
          "fg": "#abb2bf",
          "caret": "#ffcc00",
          "caretrow": "#363b43",
          "keyword": "#10b1fe",
          "comment": "#545862",
          "operator": "#7a82da",
          "function": "#3fc56b",
          "class": "#ff6480",
          "string": "#f9c859",
          "number": "#ff78f8",
          "constant": "#9f7efe",
          "attribute": "#ff936a",
          "tag": "#3691ff",
          "property": "#ce9887",
          "selection": "#3e4451",
          "invalid": "#fc2f52"
        },
        "light": {
          "bg": "#f9f9f9",
          "fg": "#383a42",
          "caret": "#f31459",
          "caretrow": "#f1f1f1",
          "keyword": "#0098dd",
          "comment": "#a0a1a7",
          "operator": "#7a82da",
          "function": "#23974a",
          "class": "#d52753",
          "string": "#c5a332",
          "number": "#ce33c0",
          "constant": "#823ff1",
          "attribute": "#df631c",
          "tag": "#275fe4",
          "property": "#a05a48",
          "selection": "#d2ecff",
          "invalid": "#ff0000"
        }
      }
      

}

**Comment by uloco** [comment]
Try this
```
{
  "workbench.startupEditor": "newUntitledFile",
  "window.zoomLevel": 0,
  "workbench.iconTheme": "material-icon-theme",
  "workbench.colorTheme": "Bluloco Light",
  "editor.fontSize": 15,
  "editor.cursorStyle": "underline",
  "editor.fontWeight": "normal"
}
```

**Comment by uloco** [comment]
Versuche mal diese Font hier, das ist die die ich verwendet habe:
https://github.com/be5invis/Iosevka
