### ISSUE TITLE
Hard to read DarkGrey foreground color in terminal

### ISSUE THREAD

**Issue by the1812** [uloco/theme-bluloco-light#33]
Many CLI tools use DarkGrey color, like typesciprt and webpack-cli. But it's hard to read under this theme.

Example in PowerShell:

```powershell
$colors = [enum]::GetValues([System.ConsoleColor])
Foreach ($bgcolor in $colors) {
    Foreach ($fgcolor in $colors) { Write-Host "$fgcolor|"  -ForegroundColor $fgcolor -BackgroundColor $bgcolor -NoNewLine }
    Write-Host " on $bgcolor"
}
```
![image](https://user-images.githubusercontent.com/26504152/109587837-b59dae80-7b42-11eb-8cb9-47d3b4f09087.png)

----

_About VSCode_

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by uloco** [comment]
Thanks for catching this! Fixed in df7850c0e28afa3b9e0c24b39e33fcaae1ccd85a
