### ISSUE TITLE
vscode-icons identifies bluloco-light as dark theme

### ISSUE THREAD

**Issue by Gliptal** [uloco/theme-bluloco-light#37]
I'm unsure whether this is an issue with [vscode-icons](https://github.com/vscode-icons/vscode-icons) or Bluloco, but vscode-icons uses the dark theme icons instead of the light themes  ones.

**Comment by uloco** [comment]
I don't quite understand the issue. Maybe it is related to vscode-icons indeed. As I tested it, the default vscode light and dark themes seem to behave identically to bluloco here. Do you have more details or screenshots about the issue?

**Comment by Gliptal** [comment]
Good point. I'll open an issue in their repo and report back.
