### ISSUE TITLE
VSCode 1.57 quick pick and sugget widget colors

### ISSUE THREAD

**Issue by Gliptal** [uloco/theme-bluloco-light#40]
See https://code.visualstudio.com/updates/v1_57#_updated-quick-pick-suggest-widget-colors.

**Comment by septsea** [comment]
Well, I encountered the problem about a month ago, but I did not consider it too serious...

**Comment by rashil2000** [comment]
I noticed this yesterday too, when 1.57 was launched. Bluloco Light is my favourite theme, but it's unusable as a result now :(

**Comment by Gliptal** [comment]
@rashil2000 For the time being an easy workaround is to add this to your settings:

````
"workbench.colorCustomizations": {
        "editorSuggestWidget.selectedBackground": "#d9d9d9",
        "editorSuggestWidget.selectedForeground": "#383a42",
        "list.focusHighlightBackground": "#d9d9d9",
        "list.focusHighlightForeground": "#383a42",
        "quickInputList.focusBackground": "#d9d9d9",
        "quickInputList.focusForeground": "#383a42"
    },
````

![Code_jOg57SICd6](https://user-images.githubusercontent.com/3907646/121695455-59e0ab00-cacb-11eb-9836-383799caa520.png)

You can change the colors based on your liiking.

**Comment by rashil2000** [comment]
Thanks @Gliptal ! 

Will try out your fixes today!

**Comment by septsea** [comment]
@Gliptal Good morning. Thanks so much!

**Comment by septsea** [comment]
I finally solved this issue by editing the extension file. I use the dark theme at night, and `workbench.colorCustomizations` overrides all themes. Thank you so much! @Gliptal

**Comment by uloco** [comment]
Thanks for the issue report, I'm currently on vacation and don't have any laptop with me to fix it properly. Hope the workarounds did work for you. I will update the theme as soon as I am back at my desk.
