### ISSUE TITLE
Gitlens (eamodio.gitlens) trailing line appears highlighted

### ISSUE THREAD

**Issue by StefanBrand** [uloco/theme-bluloco-light#46]
I find it distracting that the Gitlens trailing line is highlighted (blue background). Could you change that? I have attached an example on how other themes handle this.

These are the themable colors that Gitlens defines: https://github.com/eamodio/vscode-gitlens#themable-colors-

## Bluloco
![image](https://user-images.githubusercontent.com/8948865/129321215-d08dc531-9f3d-4d4b-b6bc-954af0de9cf0.png)

## Atom One Light
![image](https://user-images.githubusercontent.com/8948865/129321329-55e4da2f-7bb8-4275-b784-2605eefc8729.png)

**Comment by StefanBrand** [comment]
This works for me: 

```
    "workbench.colorCustomizations": {
        "[Bluloco Light Italic]": {
            "gitlens.trailingLineForegroundColor": "#0000002c"
            "gitlens.trailingLineBackgroundColor": "#0000"
        }
    }
```

![image](https://user-images.githubusercontent.com/8948865/129324904-9a33dfed-df2b-41d9-8fa5-40d66eca3214.png)

**Comment by uloco** [comment]
I just wanted to set it apart from the rest back then, but makes sense now for me too to tune it down. I'm on vacation rn, will come back to it next week.
