### ISSUE TITLE
Warnings are being colored the same way as problems.

### ISSUE THREAD

**Issue by ogierm** [uloco/theme-bluloco-light#8]
In the first line first line VS Code detected a problem and gives me an error (value not used). Those are usually underlined in green or blue.
In the second line I'm doing terrible stuff and this should indeed be underlined red.

![image](https://user-images.githubusercontent.com/29630575/56303399-1d5bd380-613c-11e9-80fb-7aadf4e8d14f.png)

This is true when using it with Java atleast, idk how the situation is with other languages.

**Comment by uloco** [comment]
I try to be very strict on warnings like that when programming, so I choose the stronger colour orange. Blue underlines are already spelling errors. Green makes no sense to me, sorry. This is a warning message and I think they should appear like that.

But you can always override that value yourself if you want in your user settings.
Tell me if you need help on doing that.

**Comment by uloco** [comment]
They both have different colors. Errors are red and warnings are orange. Perhaps the difference is not clearly enough though ...

**Comment by ogierm** [comment]
First of all: Yes, please help me with changing the colors 😅

Secondly: now that you say it I can see the difference, but it's too hard to spot.
IMO these aren't real warnings, more like "Oopsie Daisy, seems like you've forgotten to actually do something with your new object", because they don't break anything.

Obviously it's a subjective thing and I'm used to this from all the other themes. Maybe pink?

**Comment by uloco** [comment]
I think I will keep the color, because it is also wired to other parts of the theme (like terminal, lists, inputs, etc.)

Change it the way you want, then :) 

You can change the color of warning messages inside your user settings like so.
Copy this snippet insider your settings.json to get a green look of warnings

```
  "workbench.colorCustomizations": {
  "[Bluloco Light]": {
    "editorWarning.foreground": "#23974aff"
    }
  },
```
Thanks for your suggestions.

**Comment by ogierm** [comment]
Yup, worked, thank you!

**Comment by uloco** [comment]
Warning orange color is lighter and better distinguishable now in version `2.8.1`. Perhaps you should give it a try ;)
