### ISSUE TITLE
Make references a bit darker in scrollbar

### ISSUE THREAD

**Issue by ColCh** [uloco/theme-bluloco-light#9]
Using light theme

1. select some text
2. vscode highlights selected text occurence in scrollbar

These blue things are a bit hard to notice

What do you think to make it appear more contrast to scrollbar color?

![image](https://user-images.githubusercontent.com/599439/58476821-a06c4280-815a-11e9-9899-caff41bb737a.png)

it's `editorOverviewRuler.selectionHighlightForeground` vscode color and currently is has `#d2ecff` color

**Comment by uloco** [comment]
Hey @ColCh thanks for reporting. It's a bit too light indeed. Will fix in the next release. :)

**Comment by ColCh** [comment]
Thank you!

**Comment by uloco** [comment]
By the way. What do you mean by selecting it? Just clicking on it ( there will be two colors, one for variable declaration and one for usage) or do you mean highlighting it (with shift)?

**Comment by ColCh** [comment]
That's double click on word and selected highlights of same word in other places of file

**Comment by uloco** [comment]
Interesting. In some languages this color does not get triggered. For example in JavaScript, the colors from here are triggered:
```
    "editor.wordHighlightBackground": "#d9e6fd",
    "editor.wordHighlightStrongBackground": "#ecd1e5",
```

**Comment by uloco** [comment]
What do you think of this one here? It looks like it is the same blue as selection in general, but visibility is increased. I also tweaked the scrollbar colors, so that opacity is higher but the colors stay the same.

```
  "workbench.colorCustomizations": {
    "[Bluloco Light]": {
      "scrollbarSlider.activeBackground": "#00000026",
      "scrollbarSlider.hoverBackground": "#0000001a",
      "scrollbarSlider.background": "#00000012",
      "editorOverviewRuler.selectionHighlightForeground": "#8bcdffa7"
    }
  },
```

You can use this setting, until a proper fix is releaed.

**Comment by ColCh** [comment]
Oh, sorry for delay

that was actually TypeScript, not JavaScript

Thank you for settings snippet, here is result (small scrollbar is located in centre of the image):

![image](https://user-images.githubusercontent.com/599439/58718049-5216a800-83d5-11e9-8783-7b3a5a8e6605.png)


Looks much clearly now! 💪

**Comment by uloco** [comment]
Fixed it (and added a bunch of additional improvements). You can safely remove the settings now and update the extension. Feel free to create a new issue when something isn't working properly. Thanks again for reporting.
